# Generated by Django 2.1.5 on 2019-01-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_emissivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('series_id', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('ttr', models.FloatField()),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('device_address', models.IntegerField()),
                ('data_address', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_reading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelvin', models.FloatField()),
                ('celcius', models.FloatField(blank=True, null=True)),
                ('fahrenheit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_temperature',
                'managed': False,
            },
        ),
    ]
